sonar.host.url=http://localhost:9000
sonar.token=squ_ee75220213a0ff159a753997606704dbd15095f9
sonar.login=squ_ee75220213a0ff159a753997606704dbd15095f9
sonar.projectKey=mediconnect-frontend
sonar.projectName=MediConnect Frontend
sonar.projectVersion=1.0.0
sonar.sources=src
sonar.exclusions=**/node_modules/**, **/dist/**, **/*.spec.ts
sonar.sourceEncoding=UTF-8
